// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDygD5NqI2qwwVhSS48ujZx-SdwcAJSwhs',
    appId: '1:961481372234:web:0ff3f3a69013632ab0acb3',
    messagingSenderId: '961481372234',
    projectId: 'nkcc-50788',
    authDomain: 'nkcc-50788.firebaseapp.com',
    storageBucket: 'nkcc-50788.firebasestorage.app',
    measurementId: 'G-R5M6FCXP8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8KZdp7T_5CpOWpjJNFA7n3mYhu8BBzb8',
    appId: '1:961481372234:android:a78aeea64061cebcb0acb3',
    messagingSenderId: '961481372234',
    projectId: 'nkcc-50788',
    storageBucket: 'nkcc-50788.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo8Dh2h1PNMS7efURnkNTeCF1usYPSCW0',
    appId: '1:961481372234:ios:91494fcb56b76aa5b0acb3',
    messagingSenderId: '961481372234',
    projectId: 'nkcc-50788',
    storageBucket: 'nkcc-50788.firebasestorage.app',
    iosBundleId: 'com.nkcc.singlecustomerapp.activity.support',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo8Dh2h1PNMS7efURnkNTeCF1usYPSCW0',
    appId: '1:961481372234:ios:91494fcb56b76aa5b0acb3',
    messagingSenderId: '961481372234',
    projectId: 'nkcc-50788',
    storageBucket: 'nkcc-50788.firebasestorage.app',
    iosBundleId: 'com.nkcc.singlecustomerapp.activity.support',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDygD5NqI2qwwVhSS48ujZx-SdwcAJSwhs',
    appId: '1:961481372234:web:b721f548bd92fd2cb0acb3',
    messagingSenderId: '961481372234',
    projectId: 'nkcc-50788',
    authDomain: 'nkcc-50788.firebaseapp.com',
    storageBucket: 'nkcc-50788.firebasestorage.app',
    measurementId: 'G-C0424FGK1M',
  );

}